### ISSUE TITLE
Calculate AUCell scores Error:  unused argument (splitByBlocks = TRUE) 

### ISSUE THREAD

**Issue by skye-12138** [chuiqin/irGSEA#27]
**运行代码如下**
test是一个seurat object
test <- irGSEA.score(object = test, assay = "RNA", 
                             slot = "data", seeds = 123, ncores = 1,
                             min.cells = 3, min.feature = 0,
                             custom = F, geneset = NULL, msigdb = T, 
                             species = "Mus musculus", category = "H",  
                             subcategory = NULL, geneid = "symbol",
                             method = c("AUCell", "UCell", "singscore", 
                                        "ssgsea"),
                             aucell.MaxRank = NULL, ucell.MaxRank = NULL, 
                             kcdf = 'Gaussian')

运行报错：
<img width="631" alt="image" src="https://github.com/chuiqin/irGSEA/assets/49186667/b61f329d-3ad1-4edd-91c6-5f2115248b94">

**最后生成的结果**
<img width="367" alt="image" src="https://github.com/chuiqin/irGSEA/assets/49186667/780fa4ed-5eb4-4716-92b1-c05bbbc2f5c9">

无法没有计算出AUCell的值，查看了一下AUCell是安装上了的，请问是为什么出现这个问题，应该怎么解决呢

**版本信息**
AUCell 1.16.0
irGSEA 3.1.7
R 4.1.3

**Comment by chuiqin** [comment]
AUCell版本太低，升级一下AUCell版本

**Comment by skye-12138** [comment]
> AUCell

**Comment by skye-12138** [comment]
> AUCell版本太低，升级一下AUCell版本

可以了，多谢

**Comment by cxjcccc** [comment]
请问如何升级到适合自己R版本的包
